### PR TITLE
Improve evaluation ui

### PR DESCRIPTION
**Pull request by sofipacifico**
* Added new design for highlight row in evolution

### CODE REVIEW

**Comment by sofipacifico** [comment]
image

**Comment by sofipacifico** [comment]
image

**Comment by andresmoschini** [comment]
@ragojose, @jgreyling, Silvia, what do you think?

**Comment by andresmoschini** [comment]
Nice, the change is only CSS?

**Comment by sofipacifico** [comment]
Yes, only css

**Comment by andresmoschini** [comment]
It looks fine, please confirm with Jose and the owners about the behavior.

**Comment by sofipacifico** [comment]
Confirmed with Jose

**Pull request merged**
